Skip the stripping phase we are using gccgo
Running dh_strip causes:
no debug info in ELF executable errno -1
fatal error: no debug info in ELF executable

runtime stack:
no debug info in ELF executable errno -1
panic during panic